package com.apaza.moises.visitsucre.database;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.apaza.moises.visitsucre.database.category;
import com.apaza.moises.visitsucre.database.place;
import com.apaza.moises.visitsucre.database.image;

import com.apaza.moises.visitsucre.database.categoryDao;
import com.apaza.moises.visitsucre.database.placeDao;
import com.apaza.moises.visitsucre.database.imageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig categoryDaoConfig;
    private final DaoConfig placeDaoConfig;
    private final DaoConfig imageDaoConfig;

    private final categoryDao categoryDao;
    private final placeDao placeDao;
    private final imageDao imageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        categoryDaoConfig = daoConfigMap.get(categoryDao.class).clone();
        categoryDaoConfig.initIdentityScope(type);

        placeDaoConfig = daoConfigMap.get(placeDao.class).clone();
        placeDaoConfig.initIdentityScope(type);

        imageDaoConfig = daoConfigMap.get(imageDao.class).clone();
        imageDaoConfig.initIdentityScope(type);

        categoryDao = new categoryDao(categoryDaoConfig, this);
        placeDao = new placeDao(placeDaoConfig, this);
        imageDao = new imageDao(imageDaoConfig, this);

        registerDao(category.class, categoryDao);
        registerDao(place.class, placeDao);
        registerDao(image.class, imageDao);
    }
    
    public void clear() {
        categoryDaoConfig.getIdentityScope().clear();
        placeDaoConfig.getIdentityScope().clear();
        imageDaoConfig.getIdentityScope().clear();
    }

    public categoryDao getCategoryDao() {
        return categoryDao;
    }

    public placeDao getPlaceDao() {
        return placeDao;
    }

    public imageDao getImageDao() {
        return imageDao;
    }

}
